[package]
name = "ast"
version = "0.0.0"
edition.workspace = true

[dependencies]
pretty.workspace = true
cst.workspace = true
parser.workspace = true
diagnostics.workspace = true
text-size.workspace = true
common_defs.workspace = true

[dev-dependencies]
expect-test.workspace = true
